//> using publish.organization "org.virtuslab"
//> using publish.name "toolkit-alpha"
//> using publish.computeVersion "git:tag"
//> using publish.url "https://github.com/VirtusLab/toolkit"
//> using publish.versionControl "scm:git:github.com/VirtusLab/toolkit.git"
//> using publish.license "Apache-2.0"
//> using publish.repository "central"
//> using publish.developer "szymon-rd|Simon R|https://github.com/szymon-rd"