//> using scala "2.13", "3"
//> using publish.name "toolkit"
//> using lib "com.softwaremill.sttp.client4::core::4.0.0-M1"
//> using lib "com.softwaremill.sttp.client4::upickle::4.0.0-M1"
//> using lib "com.lihaoyi::upickle::3.1.0"
//> using lib "com.lihaoyi::os-lib::0.9.1"
